#Ansible Playbook to create/user/group/id/port/apache web server
---
- hosts: localhost
  become: true
  gather_facts: false
  vars_files:
    - /etc/ansible/group_vars/users.yaml
  vars:
    apache_port: 80 # input any port number
  tasks:
  - name: Create users
    user:
      name: "{{ item }}"
      shell: /bin/bash
      system: no
      append: yes
      state: present
      createhome: yes
      generate_ssh_key: true
      home: "/home/{{ item }}"
      ssh_key_bits: 4096
      ssh_key_file: .ssh/id_rsa
      ssh_key_type: rsa
    with_items:
      - "{{ names }}"
  - name: Create Group
    group:
      name: sample
      gid: 2022
      system: false

  - name: install apache2 #httpd
    package: name=apache2 update_cache=yes state=latest
  - name: start apache
    service: name=apache2 state=started


  - name: copy index file
    copy:
      src: index.html
      dest: /var/www/html/

  - name: Creating a file with content
    copy:
      dest: /var/www/html/index.html
      content: |
        KLD
        Sample Application


  - name: enabled mod_rewrite
    apache2_module: name=rewrite state=present
    notify:
      - restart apache2

  - name: apache2 listen on port {{ apache_port }}
    lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ apache_port }}" state=present
    notify:
      - restart apache2

  - name: apache2 virtualhost on port {{ apache_port }}
    lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ apache_port }}>" state=present
    notify:
      - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
                                       
